### ISSUE TITLE
Is the paper still available?

### ISSUE THREAD

**Issue by chaitjo** [deepmind/clrs#10]
Thank you for the benchmark on neural algorithmic reasoning. I love the throwback to the classical CLRS textbook! 

I remember bumping into the PDF paper online, but cannot seem to access it anymore. Is the paper associated with the repo available soon?

**Comment by PetarV-** [comment]
Hi Chaitany -- thanks so much for the kind words!

Indeed, the PDF got masked out of OpenReview at this time.
We aim to release a new version of the paper (hopefully incorporating even more tasks!) in early '22.

**Comment by PetarV-** [comment]
Hi Chaitanya,

Thank you for your patience!
We've just now released the paper on arXiv (in advance of our ICML'22 presentation):
https://arxiv.org/abs/2205.15659

**Comment by chaitjo** [comment]
Thanks!
