### ISSUE TITLE
Sampling bug on undirected weighted graphs

### ISSUE THREAD

**Issue by smahdavi4** [deepmind/clrs#61]
Hi, I think there is an issue in sampling the undirected weighted graphs. The sampled graph is first symmetrized and then weights are sampled, which makes the weights of each direction different. For algorithms that are capable of handling directed graphs, this might not cause any disruption in algorithm behavior. But, for the ones that output undirected edges (e.g., MST Kruskal), this would not be the true behavior of the algorithm.

**Comment by PetarV-** [comment]
Thank you for catching this, Sadegh!

We have now a pull request (#62) implementing a fix, which should be integrated in the codebase soon. 

We'll first run some tests internally to verify whether this change impact results strongly for algorithms like Bellman-Ford. Based on this, we can decide whether to push this change only for MSTSampler, or more generally.

**Comment by PetarV-** [comment]
This pull request is now merged and datasets regenerated.
