### ISSUE TITLE
More input signals for evaluation

### ISSUE THREAD

**Issue by smahdavi4** [deepmind/clrs#64]
Hi, in some parts of the code you increase input signals for a few algorithms for evaluation. But, the generated dataset on google storage seems to not contain them (i.e., it contains only 32 trajectories of each). Is the change going to be reflected in future versions?

**Comment by adria-p** [comment]
Hi, thank you for raising this. The current dataset on GCP should have the correct shapes and amount of samples now. Could you check that that is the case? If you are using `examples/run.py` You will need to remove your local dataset copy to force a download (which is by default stored in /tmp/CLRS30)

**Comment by smahdavi4** [comment]
Thanks for your reply. The issue seems to be still existing. I double-checked that and only 32 data points are loaded into the validation/test datasets (take the `minimum` algorithm for instance). The content of `dataset_info.json` also suggests that there are only 32 data points in the dataset.

**Comment by smahdavi4** [comment]
Yup, looks perfect. Thanks for the fix.

**Comment by smahdavi4** [comment]
Just wanted to let you know that in your `run.py`, only one batch (=32) of test data (and validation data in each iteration) is being evaluated. Full batch leads to high GPU memory consumption for test data, and average over batches would not give accurate results (e.g., F1 metric for masks).

**Comment by PetarV-** [comment]
Hi Sadegh, thank you so much for spotting this!

Indeed, the example script needs to be patched, and we will do this shortly after the Easter holiday.

The issue you point out about properly aggregating batches at test time is very important, especially when datasets are manually generated, and we will make sure to address it! Although for the specific CLRS-30 dataset we generated, this would only really impact tasks with graph mask outputs (eg. segments-intersect); in all other mask output settings we do not need to go beyond 32 trajectories, and for types other than mask I _think_ simple averaging across batches will be sufficient.

Lastly, thank you very much for your general interest in the library and all the great pointers you've had! We'd be delighted to add you to our paper's acknowledgements when it is ready for release :)

**Comment by smahdavi4** [comment]
Thank you for the detailed explanation!

**Comment by PetarV-** [comment]
Hi Sadegh, the issue of evaluating/testing on multiple batches should now be resolved by #70. 
Please let us know if any issues remain! :)

**Comment by smahdavi4** [comment]
Great! Thanks for the fix :)
