### ISSUE TITLE
Bug in KMP implementation

### ISSUE THREAD

**Issue by smahdavi4** [deepmind/clrs#67]
Hi, I think there is a bug in the KMP implementation. It does not find a match for some inputs in the dataset (i.e., outputs the end of the string).

**Comment by PetarV-** [comment]
Thank you for catching this, Sadegh!

Indeed, there was an issue with KMP's handling of a '-1' node that we initially tried to circumvent.
We now have a patch for this in #69, and at least on 2,000 randomly generated strings, the output of KMP matches the output of the naïve string matcher.

The patch will be merged (and data regenerated) during the next day or two. Thanks!

**Comment by PetarV-** [comment]
Hi Sadegh, this should now be patched!

Could you verify this on your end (and close the issue if so)? Thanks again for spotting it.

**Comment by smahdavi4** [comment]
Hi Petar, yes it's fixed now. Thanks for the patch.
